"""empty message

Revision ID: 56683a24e65d
Revises: c8a3247e5f1f
Create Date: 2023-04-27 17:12:09.864286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56683a24e65d'
down_revision = 'c8a3247e5f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
